### ISSUE TITLE
Todo List for v2.1

### ISSUE THREAD

**Issue by karpitony** [karpitony/eft-where-am-i#29]
- [ ] 자동 FullScreen 옵션 추가
- [ ] 자동 스크린샷 삭제
- [ ] 다언어 지원

**Comment by karpitony** [comment]
웹뷰 UI 교체 메모용
- [x] UI 교체하기
- [x] 콤보박스 연결하기
- [x] 버튼 연결하기
- [x] 링크 연결하기
- [x] 체크박스 상태 미리 불러오기
